### ISSUE TITLE
Client side terrain generation

### ISSUE THREAD

**Issue by bensku** [starandserpent/TerraServer#26]
Implement a chunk type that contains only a seed (or few seed values). Generate blocks from it as needed on client side. Use it only when area has not been modified and can be generated fast.

**Comment by Pawlost** [comment]
We are using Weltschmerz

**Comment by Pilvinen** [comment]
This is actually not resolved by using Weltschmerz.

The idea is client side generation by sending only a seed value over. This is potentially going to save _a lot_ of networking data.

Instead of sending over chunk data full of blocks generated on the server and shared with all the clients we would be sending over a compact seed value which allows that chunk to be generated on the client.

It would be a sort of "locally run Weltschmerz" if you will. But obviously we can't pre-share all of the data because of the huge cheating potential this has, so a lot of idea sessions and planning are required before we can move forward with an actual implementation.

But I'm re-opening the issue.

**Comment by Pawlost** [comment]
If I understand this right it is related to single material ID reference.

**Comment by Pilvinen** [comment]
This is separate from material ID reference. 

This has to do with using a seed for random number generation and using that master seed to create a ton of child seeds for each chunk.

So therefore a chunk type which contains a seed.

However it does have some inherent problems and this needs to be discussed one on one.

**Comment by Pawlost** [comment]
This issue was moved to our private wiki.
